# 环境变量配置
environment:
  rag_data_dir: "{ROOTPATH}/data/rag_data"
  shot_data_dir: "{ROOTPATH}/data/rag_data/few_shots"
  log_dir: "{ROOTPATH}/logs"
  scl_plan: "{ROOTPATH}/data/rag_data/scl/scl_case_plan"
  instruction_dir: "{ROOTPATH}/data/rag_data/instructions"

# 模型配置
model:
  name: "gpt-4.1-mini"  # 可选: claude-3-5-sonnet-20241022, claude-3-5-haiku-20241022, llama3.1-8b-instruct
  max_tokens: 16384
  temperature: 0.1
  top_p: 0.9

# 检索模型配置
retrieve:
  model: "glm-4-plus"
  temperature: 0.15
  top_p: 0.9

# 模型器设置
modeler:
  plan_set_name: "scl_case_plan_NOfewshot"

# 验证代理配置
verify:
  count: 5
  openness: "http://192.168.103.152:9000"

# RAG检索配置
retrieval:
  case_alternatives:
    - "LGF_CompareString"
    - "LGF_BitCount"
    - "LGF_SinusCI"
  b25_model: "BM25Okapi"

# 指令配置
instruction:
  path:
    - "{ROOTPATH}/data/rag_data/instructions/basic.jsonl"
    - "{ROOTPATH}/data/rag_data/instructions/extend.jsonl"
  score_threshold: 0.5
  top_k: 2

# 工作流实验设置
workflow:
  retrieve_disabled: false
  modeling_disabled: True
  debugger_disabled: false